### ISSUE TITLE
Forms 3.4 causes crash when init the plugin

### ISSUE THREAD

**Issue by raymondjstone** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#57] opened 2018-11-29 09:37 UTC
PullToRefreshLayoutRenderer.Init(); fails (android in this case)

Unhandled Exception:

System.TypeLoadException: VTable setup of type Refractored.XamForms.PullToRefresh.Droid.PullToRefreshLayoutRenderer failed

**Comment by nielscup** [comment] 2018-11-30 09:46
same issue here, only on Android. iOS works fine

**Comment by quentinR0bert** [comment] 2018-11-30 11:33
see #56

**Comment by jamesmontemagno** [comment] 2018-11-30 17:21
Duplicate of #56

**Closed by jamesmontemagno** 2018-11-30 17:21 UTC
