### ISSUE TITLE
iOS: UIRefreshControl always black on first refresh

### ISSUE THREAD

**Issue by TinaGen** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#54] opened 2018-09-21 17:01 UTC
It seems the Refresh indicator always defaults to black on the first refresh, only on iOS.

I've set the `UIRefreshControl.Appearance.TintColor` in the AppDelegate and in the OnElementChanged of my ListViewRender. 

Every subsequent refresh, the color is correct. 

Exact same issue described here: [https://bugzilla.xamarin.com/show_bug.cgi?id=34966](https://bugzilla.xamarin.com/show_bug.cgi?id=34966)

**Comment by Miiite** [comment] 2019-02-15 09:11
The associated bugzilla has been closed / resolved, and I can't reproduce it on my side. I think we can close this one.

**Comment by taublast** [comment] 2019-07-15 12:41
@TinaGen hi you can fork and fix the renderer youself (fixed for the case with a tableview, you can do same for scrollview, collectionview etc):

 ```
 bool TryInsertRefresh(UIView view, int index = 0)
        {
            this.refreshControlParent = view;

            if (view is UITableView)
            {
                var uiTableView = view as UITableView;
                uiTableView = view as UITableView;
                view.InsertSubview(refreshControl, index);

                #region bug fixed
                //fixed bug initial tint color is default
                if (uiTableView.ContentOffset.Y == 0)
                {
                    uiTableView.ContentOffset = new CGPoint(0, -refreshControl.Frame.Size.Height);
                }
                #endregion 

                return true;
            }
...
```

**Comment by BogdanoVolcano** [comment] 2019-07-15 17:54
I have the same issue.

**Closed** 2019-11-16 19:15 UTC
