### ISSUE TITLE
ObjectDisposedException: Cannot access a disposed object. Object name: 'Refractored.XamForms.PullToRefresh.Droid.PullToRefreshLayoutRenderer'.

### ISSUE THREAD

**Issue by draugaslt** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#32] opened 2017-10-26 17:41 UTC
Android: 6.0.1
Android Build: MMB29M
Manufacturer: OnePlus
Model: ONE A2003
CrashReporter Key: 17ddf61a-51bb-4433-8151-d8bad4953225
Start Date: 2017-10-26T17:11:27.465Z
Date: 2017-10-26T17:15:00.548Z

Xamarin Exception Stack:
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Refractored.XamForms.PullToRefresh.Droid.PullToRefreshLayoutRenderer'.
  at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <1d799d87381c4db5b1252825fd105b84>:0
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualBooleanMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <1d799d87381c4db5b1252825fd105b84>:0
  at Android.Views.View.get_IsInLayout () [0x0000a] in <c82a099136944d8aa96281cf061cbc12>:0
  at Xamarin.Forms.Platform.Android.VisualElementTracker.MaybeRequestLayout () [0x00016] in <398cf4d138ad48c7a756f39dfc252737>:0
  at Xamarin.Forms.Platform.Android.VisualElementTracker.HandleRedrawNeeded (System.Object sender, Xamarin.Forms.Internals.EventArg`1[T] e) [0x00049] in <398cf4d138ad48c7a756f39dfc252737>:0
  at (wrapper delegate-invoke) System.EventHandler`1[Xamarin.Forms.Internals.EventArg`1[Xamarin.Forms.VisualElement]]:invoke_void_object_TEventArgs (object,Xamarin.Forms.Internals.EventArg`1<Xamarin.Forms.VisualElement>)
  at Xamarin.Forms.VisualElement.BatchCommit () [0x00031] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.set_Bounds (Xamarin.Forms.Rectangle value) [0x00071] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.Layout (Xamarin.Forms.Rectangle bounds) [0x00000] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion (Xamarin.Forms.VisualElement child, Xamarin.Forms.Rectangle region) [0x0016b] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Grid.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height) [0x00152] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Layout.UpdateChildrenLayout () [0x000c7] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Layout.OnSizeAllocated (System.Double width, System.Double height) [0x0000f] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.SizeAllocated (System.Double width, System.Double height) [0x00000] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.SetSize (System.Double width, System.Double height) [0x00021] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.set_Bounds (Xamarin.Forms.Rectangle value) [0x0006c] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.Layout (Xamarin.Forms.Rectangle bounds) [0x00000] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion (Xamarin.Forms.VisualElement child, Xamarin.Forms.Rectangle region) [0x0016b] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.AbsoluteLayout.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height) [0x00046] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Layout.UpdateChildrenLayout () [0x000c7] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Layout.OnSizeAllocated (System.Double width, System.Double height) [0x0000f] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.SizeAllocated (System.Double width, System.Double height) [0x00000] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.SetSize (System.Double width, System.Double height) [0x00021] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.set_Bounds (Xamarin.Forms.Rectangle value) [0x0006c] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.Layout (Xamarin.Forms.Rectangle bounds) [0x00000] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion (Xamarin.Forms.VisualElement child, Xamarin.Forms.Rectangle region) [0x0016b] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Page.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height) [0x0010d] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Page.UpdateChildrenLayout () [0x000c6] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Page.OnSizeAllocated (System.Double width, System.Double height) [0x0000f] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Common.Pages.BaseContentPage.OnSizeAllocated (System.Double width, System.Double height) [0x00000] in <aa4148d4f7b047d6b0e2f30b307d3c67>:0
  at Xamarin.Forms.VisualElement.SizeAllocated (System.Double width, System.Double height) [0x00000] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.SetSize (System.Double width, System.Double height) [0x00021] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.set_Bounds (Xamarin.Forms.Rectangle value) [0x0006c] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.Layout (Xamarin.Forms.Rectangle bounds) [0x00000] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion (Xamarin.Forms.VisualElement child, Xamarin.Forms.Rectangle region) [0x0000a] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Page.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height) [0x0010d] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Page.UpdateChildrenLayout () [0x000c6] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Page.OnSizeAllocated (System.Double width, System.Double height) [0x0000f] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.SizeAllocated (System.Double width, System.Double height) [0x00000] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Page.ForceLayout () [0x0000d] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Page.set_ContainerArea (Xamarin.Forms.Rectangle value) [0x0001d] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Platform.Android.AppCompat.TabbedPageRenderer.OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x000da] in <398cf4d138ad48c7a756f39dfc252737>:0
  at Xamarin.Forms.Platform.Android.FormsViewGroup.n_OnLayout_ZIIII (System.IntPtr jnienv, System.IntPtr native__this, System.Boolean p0, System.Int32 p1, System.Int32 p2, System.Int32 p3, System.Int32 p4) [0x00008] in <e0b7802c8dd141c9a08bc5c8ecb6bbd9>:0
  at (wrapper dynamic-method) System.Object:617584bb-3014-41c5-bc70-45528c2fcd9f (intptr,intptr,bool,int,int,int,int)

**Comment by jamesmontemagno** [comment] 2017-10-27 17:49
Duplicate of #12

**Closed by jamesmontemagno** 2017-10-27 17:49 UTC
