### ISSUE TITLE
Crash on Xamarin Android

### ISSUE THREAD

**Issue by bastianbecker21** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#44] opened 2018-04-06 08:38 UTC
```
<controls:PullToRefreshLayout
      IsPullToRefreshEnabled="True"
      RefreshCommand="{Binding RefreshCommand}"
      IsRefreshing="{Binding IsBusy}"
      RefreshColor="Blue"> 
      <ScrollView
      HorizontalOptions="FillAndExpand"
      VerticalOptions="FillAndExpand">
        <StackLayout
              HorizontalOptions="FillAndExpand"
              VerticalOptions="FillAndExpand">
            <BoxView HeightRequest="100" WidthRequest="100" BackgroundColor="Blue"/>
            <BoxView HeightRequest="100" WidthRequest="100" BackgroundColor="Red"/>
            <BoxView HeightRequest="100" WidthRequest="100" BackgroundColor="Yellow"/>
            <BoxView HeightRequest="100" WidthRequest="100" BackgroundColor="Purple"/>
            <BoxView HeightRequest="100" WidthRequest="100" BackgroundColor="Maroon"/>
            <BoxView HeightRequest="100" WidthRequest="100" BackgroundColor="Blue"/>
            <BoxView HeightRequest="100" WidthRequest="100" BackgroundColor="Red"/>
            <BoxView HeightRequest="100" WidthRequest="100" BackgroundColor="Yellow"/>
            <BoxView HeightRequest="100" WidthRequest="100" BackgroundColor="Purple"/>
            <BoxView HeightRequest="100" WidthRequest="100" BackgroundColor="Maroon"/>
        </StackLayout>
      </ScrollView>
  </controls:PullToRefreshLayout>
```
This package works good in general but it crashes when the content size is changed.
The views of StackLayout inner ScrollView of my project is changed dynamically.
Some views are not shown in some case, so the content size get smaller than ScrollView size.

In this case, the app crashes with "Cannot access a disposed object"
Please help me to fix this issue soon.

Thanks!

**Comment by conradh** [comment] 2018-06-07 13:32
I have the same issue now. In my case 100% reproducible if navigating through all my 5 tabs (where 2 of them has pulltorefreshlayout) Then i click a button to do a pushhmodal(navigationpage), I navigate 2 steps and click on an editfield that triggers the keyboard to popup and also scroll the view. Thereby some onLayout-thingy crashes on:

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Refractored.XamForms.PullToRefresh.Droid.PullToRefreshLayoutRenderer'.

**Comment by stesvis** [comment] 2018-06-19 17:45
Same is happening to me.
I use the **PullToRefreshLayout** in some pages, but then when i navigate to a page with <Entry> elements (this page doesn't contain a **PullToRefreshLayout**), it crashes as soon as i click on the text box and the keyboard shows.

> Unhandled Exception:
> 
> System.ObjectDisposedException: Cannot access a disposed object.
> Object name: 'Refractored.XamForms.PullToRefresh.Droid.PullToRefreshLayoutRenderer'.

Only on Android. iOS works fine.

**Comment by jamesmontemagno** [comment] 2019-02-13 04:52
Duplicate of #12

**Closed by jamesmontemagno** 2019-02-13 04:52 UTC
