### ISSUE TITLE
PullToRefreshLayout - Refresher does not hide after set IsRefreshing to false

### ISSUE THREAD

**Issue by viniciusmaia** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#49] opened 2018-04-23 19:31 UTC
I'm using PullToRefreshLayout with Prism MVVM, I have a bool property in ViewModel to bind for IsRefreshing called IsBusy and when I set IsBusy to false, the refresher still appear on the page.

**Comment by JunkyXL86** [comment] 2018-04-25 11:55
I faced the same issue. I think it's because the IsRefreshing property does not recognize an immediate reset of the current value. 
It seems that the refresher spins forever because it never got notified about the false value. So I inserted a await Task.Delay(50) so that the UI has enough time to reflect the property change.
->
IsRefreshing = true;
await Task.Delay(50);
IsRefreshing = false;

**Comment by jamesmontemagno** [comment] 2018-04-25 17:42
Would need a sample app to see what your issue is.

**Comment by jochembroekhoff** [comment] 2018-05-02 10:41
In my case, it was resolved by using Device.BeginInvokeOnMainThread: `Xamarin.Forms.Device.BeginInvokeOnMainThread(() => IsRefreshing = false);`

**Comment by meauris** [comment] 2018-06-25 17:30
Same issue here, I am using PullToRefreshLayout in the same situation as @viniciusmaia describes.
Both the 'solutions' of @JunkyXL86 and @jochembroekhoff provided me a workaround.

**Comment by KristofferBerge** [comment] 2018-07-13 10:04
There is definitely something up with the IsRefreshing property. In my case I am only able to update it if I directly reference the control. On Android

Xaml
```
            <refresh:PullToRefreshLayout x:Name="PullToRefreshLayout" IsPullToRefreshEnabled="True"
                                         RefreshCommand="{Binding RefreshCommand}"
                                         IsRefreshing="{Binding IsRefreshing}">
                <wwr:FormsWebView x:Name="WebViewElement" OnContentLoaded="OnContentLoaded"/>
            </refresh:PullToRefreshLayout>
```

Codebehind
```
        private ICommand refreshCommand;
        public ICommand RefreshCommand
        {
            get { return refreshCommand; }
            set
            {
                if (value == refreshCommand)
                    return;

                refreshCommand = value;
                OnPropertyChanged(nameof(RefreshCommand));
            }
        }

        private bool isRefreshing;
        public bool IsRefreshing
        {
            get { return isRefreshing; }
            set
            {
                //note that it's raising the property change event even when the value set is the same
                isRefreshing = value;
                OnPropertyChanged(nameof(IsRefreshing));
            }
        }
        public MyComponent()
        {
            InitializeComponent();
            RefreshCommand = new Command(RefreshPage, CanRefresh);
        }
        
        void RefreshPage()
        {
            WebViewElement.Refresh();

            // Only way to remove the loading
            //PullToRefreshLayout.IsRefreshing = false;
            
            // Still nothing
            Device.BeginInvokeOnMainThread(async() =>
            {
                await Task.Delay(50);
                IsRefreshing = false;
            });
        }

        // Even when webview has finished loading, updating the boolean has no effect
        private void OnContentLoaded(object sender, EventArgs e)
        {
            IsRefreshing = false;
        }
```

**Comment by SunnyMukherjee** [comment] 2018-09-26 02:28
Solution from @jochembroekhoff worked for me.  

I used the MainThread class in the Xamarin.Essentials package like below.

```
 MainThread.BeginInvokeOnMainThread
                                (
                                    () =>
                                    {
                                        IsRefreshing = false;
                                    }
                                );
```

**Comment by RonnyBansemer** [comment] 2018-12-14 23:04
I'm facing the same problem:

**XAML:**
```XAML
<ptr:PullToRefreshLayout IsPullToRefreshEnabled="{Binding Path=CloudService.IsReachable}"
                         RefreshCommand="{Binding Path=RefreshMasterDataCommand}"
                         IsRefreshing="{Binding Path=MasterDataIsRefreshing}">
   <ScrollView> 
      <!-- some stuff -->
   </ScrollView>
</ptr:PullToRefreshLayout>
```

**ViewModel:**

```C#
class MyVM : INotifyPropertyChanged
{
      DelegateCommand _refreshMasterDataCommand;
      public DelegateCommand RefreshMasterDataCommand => _refreshMasterDataCommand ?? (_refreshMasterDataCommand = new DelegateCommand(OnRefreshMasterDataExecuted));

      void OnRefreshMasterDataExecuted()
      {
         MasterDataIsRefreshing = true;
         NavigateAsync($"{nameof(Views.MasterDataUpdateModalPage)}", useModalNavigation: true);
         MasterDataIsRefreshing = false;
      }

      public bool MasterDataIsRefreshing { get; set; }
}
```
OnPropertyChanged is implemented using ProperyChanged.Fody and works fine for all other Properties. 

**ViewModel (even not working:**

```C#
class MyVM : INotifyPropertyChanged
{
      DelegateCommand _refreshMasterDataCommand;
      public DelegateCommand RefreshMasterDataCommand => _refreshMasterDataCommand ?? (_refreshMasterDataCommand = new DelegateCommand(OnRefreshMasterDataExecuted));

      void OnRefreshMasterDataExecuted()
      {
         MasterDataIsRefreshing = true;
         NavigateAsync($"{nameof(Views.MasterDataUpdateModalPage)}", useModalNavigation: true);
         MainThread.BeginInvokeOnMainThread(() => MasterDataIsRefreshing = false);
      }

      public bool MasterDataIsRefreshing { get; set; }
}
```

**Comment by nielscup** [comment] 2018-12-27 16:41
same problem here

**Comment by draco961** [comment] 2019-01-29 09:52
Same problem :-) 
This in the ViewModel solved the problem, Thanks Jochem for the tip 
Xamarin.Forms.Device.BeginInvokeOnMainThread(() => IsRefreshing = false);

**Comment by wint100** [comment] 2019-02-16 21:28
Same issue and same fix as above

**Comment by phlashdev** [comment] 2019-03-13 12:48
I've used the layout in multiple views in our project. The same problem occurs only on one view, on the others everything works as expected. But I wasn't able yet to determine what is causing the issue.

Note: the "BeginInvokeOnMainThread"-Fix worked for me too!

**Comment by gaocan1992** [comment] 2019-04-24 20:21
First I thought it is because the binding mode issue. So we cannot change value and let it propagate from view controller to layout itself. I modified the code like this:
```
/// <summary>
        /// The is refreshing property.
        /// </summary>
        public static readonly BindableProperty IsRefreshingProperty =
            BindableProperty.Create(nameof(IsRefreshing), typeof(bool), typeof(PullToRefreshLayout), false, BindingMode.TwoWay, propertyChanged: OnIsRefreshingChanged);

        protected static void OnIsRefreshingChanged(BindableObject bindable, object oldValue, object newValue) {
            var pullToRefreshLayout = bindable as PullToRefreshLayout;
            if (pullToRefreshLayout == null) return;
            pullToRefreshLayout.IsRefreshing = (bool)newValue;
        }

        /// <summary>
        /// Gets or sets a value indicating whether this instance is refreshing.
        /// </summary>
        /// <value><c>true</c> if this instance is refreshing; otherwise, <c>false</c>.</value>
        public bool IsRefreshing {
            get { return (bool)GetValue(IsRefreshingProperty); }
            set { SetValue(IsRefreshingProperty, value); }
        }
```

However it doesn't work (it should but I could figure out why)
```
<controls:PullToRefreshLayout x:Name="PullToRefreshLayout"
                                  IsPullToRefreshEnabled="True"
                                  RefreshCommand="{Binding RefreshCommand}">
```

```
PullToRefreshLayout.IsRefreshing = true;
await LoadAsync();
PullToRefreshLayout.IsRefreshing = false;
```

This is what I have done to make it works.

**Comment by scriptBoris** [comment] 2019-06-10 08:21
Hello author, can you tell when this problem will be solved into **NugetPackage**?

**Comment by JunkyXL86** [comment] 2019-06-28 09:25
Can someone create an ultra simple fully working sample app that reproduces this behavior?

**Comment by RedasP** [comment] 2019-06-28 12:31
In my case, this issue occurs intermittently.

**Comment by jamesmontemagno** [comment] 2020-02-12 23:11
Please use the RefreshView as this is officially deprecated now https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/refreshview

**Closed by jamesmontemagno** 2020-02-12 23:11 UTC

**Comment by predalpha** [comment] 2022-10-15 19:35
I've recently encountered the same issue with the refreshView. I dont use prism but i use MVVM with the community control toolkit.
Solved by explicitely setting the binding mode to **OneWay** :

` <RefreshView x:DataType="local:myViewModel" Padding="20,10" Command="{Binding PageAppearingCommand}" IsRefreshing="{Binding IsBusy, Mode=OneWay}">`
